name: 🚀 Deploy on push

on:
  push:
    branches:
      - master

jobs:
  deploy-master:
    name: 🎉 Deploy to Master
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Deploy to server via ssh
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: "export APP_ENV=${{ secrets.APP_ENV }} && sh /var/bash_script/dashboard-ppal.sh"
